FROM alpine:latest
RUN apk add --no-cache openjdk8
RUN apk add --no-cache curl
WORKDIR /opt/appdynamics/machine-agent
COPY --from=dtr.corp.appdynamics.com/appdynamics/machine-agent /opt/appdynamics/machine-agent .
# remove once new snapshot for appd commons 2.2.1 is created
RUN rm lib/guava*
WORKDIR /opt/appdynamics/machine-agent/monitors
COPY target/CouchDBMonitor-*.zip CouchDBMonitor.zip
RUN unzip -q CouchDBMonitor.zip && \
    rm CouchDBMonitor.zip
WORKDIR /opt/appdynamics/machine-agent/monitors/CouchDBMonitor
COPY src/integration-test/resources/conf/config.yml config.yml
# Setup JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
ENV PATH="$JAVA_HOME/bin:${PATH}"
CMD ["sh", "-c", "java -jar couchdb-monitoring-extension.jar"]