# List of couchdb instances
servers:
  - host: "localhost"
    port: 5984
    username: "anna"
    password: "secret"
    displayName: "localhost"


#prefix used to show up metrics in AppDynamics
metricPrefix:  "Custom Metrics|CouchDB|"

