#This will create this metric in all the tiers, under this path
metricPrefix: Custom Metrics|CouchDB|

#This will create it in specific Tier/Component.
#Make sure to replace <COMPONENT_ID> with the appropriate one from your environment.
#To find the <COMPONENT_ID> in your environment, please follow the screen shot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
#metricPrefix: Server|Component:10|Custom Metrics|CouchDB|


servers:
  - uri: 'http://127.0.0.1:5984'
    username: 'admin' # user should have privilege in CouchDB to view stats and view info
    password: 'admin'
    encryptedPassword: ''
    useSSL: 'false'
    displayName: 'myCluster'

# more servers go here
  - uri: 'https://localhost:6984'
    username: 'admin'
    password: 'admin'
    encryptedPassword: ''
    useSSL: 'true'
    displayName: 'testCluster'


nodes: [".*"]

connection:
  socketTimeout: 5000 # Read Timeout
  connectTimeout: 5000 # Connection Timeout

  sslCertCheckEnabled: true #
  sslCipherSuites: [] # Defaults to "default".
  sslVerifyHostname: true
  sslProtocols: [] # If null, by default TLSv1, TLSv1.1, TLSv1.2 are supported.

  #Converting PEM to JKS https://docs.oracle.com/cd/E35976_01/server.740/es_admin/src/tadm_ssl_convert_pem_to_jks.html
  sslTrustStorePath: "" # If not set, will set value from "-Dappdynamics.agent.monitors.truststore.path=/path/cacerts" if present, else will set value as <MachineAgentHome>/conf/extensions-cacerts.jks.
  sslTrustStorePassword: "changeit" # If not set, will set value from "-Dappdynamics.agent.monitors.truststore.password".
  sslTrustStoreEncryptedPassword: "" ## If not set, will set value from "-Dappdynamics.agent.monitors.truststore.encryptedPassword".

proxy:
  uri: ""
  username: ""
  password: ""
  encryptedPassword: ""

encryptionKey: "myKey"

# numberOfThreads = number of servers
numberOfThreads: 2

metricPathReplacements:
  - replace: "_"
    replaceWith: "%"
  - replace: "percent"
    replaceWith: "%"

customDashboard:
  enabled: true
  dashboardName: "CouchDB Monitor Dashboard"
  sslCertCheckEnabled: true
  # Update the path to the dashboard file.
  pathToSIMDashboard: "monitors/CustomDashboard_Redis+Enterprise_Dashboard.json"
  pathToNormalDashboard:
  periodicDashboardCheckInSeconds: 300

# If any of the following fields are not set, the values of the specific fields are set from the system properties of the corresponding fields as specified in the comments.
# If the system properties are not set for the field, then the data is retrieved from machine agent configFile. Please refer to ControllerInfoFactory for more details.
controllerInfo:
  controllerHost: "" # -Dappdynamics.controller.hostName
  controllerPort: 8090 # -Dappdynamics.controller.port
  controllerSslEnabled: false # -Dappdynamics.controller.ssl.enabled
  enableOrchestration: false # N/A
  uniqueHostId: "" # -Dappdynamics.agent.uniqueHostId
  username: "" # -Dappdynamics.agent.monitors.controller.username
  password: "" # -Dappdynamics.agent.monitors.controller.password
  encryptedPassword: "" # -Dappdynamics.agent.monitors.controller.encryptedPassword
  accountAccessKey: "" # -Dappdynamics.agent.accountAccessKey
  account: "customer1" # -Dappdynamics.agent.accountName
  machinePath: "" # -Dappdynamics.machine.agent.hierarchyPath
  simEnabled: false # -Dappdynamics.sim.enabled
  applicationName: "" # -Dappdynamics.agent.applicationName
  tierName: "" # -Dappdynamics.agent.tierName
  nodeName: "" # -Dappdynamics.agent.nodeName

enableHealthChecks: true # If not set, will be retrieved from "-Dappdynamics.agent.monitors.healthchecks.enable=true". Defaults to true.